auth:
  defaultQuota:
    maxSessions:          1
    maxIdleSessionTTL:    60
    maxPacketSize:        65535
    maxPacketIdentifiers: 10
    maxQueueSizeQoS0:     100
    maxQueueSizeQoS1:     100
    maxQueueSizeQoS2:     100
  principalDirs:
    - "/etc/hummingbird/principals"
    - "./resources/principals"

admin:
  socketPath: "hummingbird.sock"

transports:
  - type: socket
    bindAddress: 0.0.0.0
    bindPort: 1883
    listenBacklog: 16
    connectionLimit: 1024
  - type: websocket
    transport:
      type: socket
      bindAddress: 0.0.0.0
      bindPort: 1884
      listenBacklog: 5
  - type: tls
    transport:
      type: socket
      bindAddress: 0.0.0.0
      bindPort: 8883
      listenBacklog: 5
    wantClientCert: true
    crtFilePath: resources/hummingbird_server.crt
    keyFilePath: resources/hummingbird_server.key

prometheus:
  bindAddress: "*"
  bindPort: 9001

logging:
  level: INFO
  appenders:
    - type: console
