auth:
  credentials:
    "mqtt-default":
      "$2y$14$z1TeFmnk9zirP1Ml55lVyuOWOhaYyqlHlvd6meaze2KDYPH8hrdsS"
  permissions:
    "mqtt-default":
      "#":
        "!": [ PUB, SUB ]

admin:
  socketPath: "/var/run/hummingbird/hummingbird.socket"

servers:
  - maxMessageSize: 100000
    transport:
      type: socket
      bindAddress: 0.0.0.0
      bindPort: 1883
      listenBacklog: 5
  - maxMessageSize: 100000
    transport:
      type: websocket
      transport:
        type: socket
        bindAddress: 0.0.0.0
        bindPort: 1884
        listenBacklog: 5
#  - type: tls
#    transport:
#      type: socket
#      bindAddress: 0.0.0.0
#      bindPort: 8883
#      listenBacklog: 5
#    wantClientCert: true
#    caFilePath: ca.pem
#    crtFilePath: my-cert.crt
#    keyFilePath: my-key.pem
#  - type: websocket
#    transport:
#      type: tls
#      transport:
#        type: socket
#        bindAddress: 0.0.0.0
#        bindPort: 8884
#        listenBacklog: 5
#      wantClientCert: false
#      caFilePath: ca.pem
#      crtFilePath: my-cert.crt
#      keyFilePath: my-key.pem

logging:
  level: INFO
  appenders:
    - type: syslog
    - type: console
