auth:
  credentials:
    "mqtt-default":
      "$2y$14$z1TeFmnk9zirP1Ml55lVyuOWOhaYyqlHlvd6meaze2KDYPH8hrdsS"
  permissions:
    "mqtt-default":
      "#":
        "!": [ PUB, SUB ]
    "example":
      "#":
        "!": [ SUB ]
      "subtree":
        "!": [ PUB ]
        ">":
          "deep":
            "!": [ PUB ]
          "deeper":
            ">":
              "evendeeper":
                ">":
                  "#":
                    "!": [PUB]

admin:
  socketPath: "hummingbird.socket"

transports:
  - type: socket
    bindAddress: 0.0.0.0
    bindPort: 1883
    listenBacklog: 5
  - type: websocket
    transport:
      type: socket
      bindAddress: 0.0.0.0
      bindPort: 1884
      listenBacklog: 5
  - type: tls
    transport:
      type: socket
      bindAddress: 0.0.0.0
      bindPort: 8883
      listenBacklog: 5
    wantClientCert: false
    caFilePath: ca.crt
    crtFilePath: cert.crt
    keyFilePath: cert.pem

logging:
  level: DEBUG
  appenders:
    - type: console
