auth:
  defaultQuota:
    sessionTTL: 0
  principals:
    e4f7f759-a7f0-4ae7-8140-766269e1c503:
      username: "mqtt-default"
      password: "$2y$14$z1TeFmnk9zirP1Ml55lVyuOWOhaYyqlHlvd6meaze2KDYPH8hrdsS"
      quota:
        sessionTTL: 60
      permissions:
        "abc":
          "/":
            "def":
              "?": [ SUB ]
            "#":
              "?": [ PUB ]

admin:
  socketPath: "hummingbird.socket"

transports:
  - type: socket
    bindAddress: 0.0.0.0
    bindPort: 1883
    listenBacklog: 5
  - type: websocket
    transport:
      type: socket
      bindAddress: 0.0.0.0
      bindPort: 1884
      listenBacklog: 5
  - type: tls
    transport:
      type: socket
      bindAddress: 0.0.0.0
      bindPort: 8883
      listenBacklog: 5
    wantClientCert: false
    caFilePath: ca.crt
    crtFilePath: cert.crt
    keyFilePath: cert.pem

logging:
  level: DEBUG
  appenders:
    - type: console
