auth:
  credentials:
    "mqtt-default":
      "$2y$14$z1TeFmnk9zirP1Ml55lVyuOWOhaYyqlHlvd6meaze2KDYPH8hrdsS"
  permissions:
    "mqtt-default":
      "#":
        "!": [ PUB, SUB ]

admin:
  socketPath: "/var/run/hummingbird/hummingbird.socket"

transports:
  - type: socket
    bindAddress: 0.0.0.0
    bindPort: 1883
    listenBacklog: 5
  - type: websocket
    transport:
      type: socket
      bindAddress: 0.0.0.0
      bindPort: 1884
      listenBacklog: 5

logging:
  level: INFO
  appenders:
    - type: syslog
