resolver: lts-7.19
packages:
  - '.'
#  - '../haskell-mqtt'
  - location:
      git: https://github.com/lpeterse/haskell-mqtt.git
      commit: b7e5f1c212d6ca529e32ed24d8123396223bcebd
extra-deps:
  - mqtt-0.1.0.0
  - socket-0.8.0.1
  - socket-unix-0.2.0.0
  - aeson-1.1.0.0
flags: {}
extra-package-dbs: []
