resolver: lts-9.17
packages:
- "."
extra-deps:
  - socket-unix-0.2.0.0
  - websockets-0.12.1.0
  - git: https://github.com/lpeterse/haskell-mqtt.git
    commit: 532af76d7a8148241108bbabb0b6229dcc2aa3ab
flags: {}
extra-package-dbs: []
