resolver: lts-9.0
packages:
  - '.'
#  - '../haskell-mqtt'
  - location:
      git: https://github.com/lpeterse/haskell-mqtt.git
      commit: 0dc6532f4d720c619c8151035caf11b1f676c437
extra-deps:
  - mqtt-0.3.0.0
  - socket-unix-0.2.0.0
  - websockets-0.12.1.0
flags: {}
extra-package-dbs: []
