resolver: lts-7.19
packages:
  - '.'
#  - '../haskell-mqtt'
  - location:
      git: https://github.com/lpeterse/haskell-mqtt.git
      commit: b10d54d6dc8fcf18ab7db7ef978654086070d660
extra-deps:
  - mqtt-0.1.1.0
  - socket-0.8.0.1
  - socket-unix-0.2.0.0
  - aeson-1.1.0.0
  - websockets-0.10.0.0
  - tls-1.3.10
flags: {}
extra-package-dbs: []
