resolver: lts-7.19
packages:
  - '.'
#  - '../haskell-mqtt'
  - location:
      git: https://github.com/lpeterse/haskell-mqtt.git
      commit: a382da12c189362cca4b2568ad29168911261b07
extra-deps:
  - mqtt-0.1.0.0
  - socket-0.8.0.1
  - socket-unix-0.2.0.0
  - aeson-1.1.0.0
flags: {}
extra-package-dbs: []
