resolver: lts-7.19
packages:
  - '.'
#  - '../haskell-mqtt'
  - location:
      git: https://github.com/lpeterse/haskell-mqtt.git
      commit: 31f5d7f1b38602e132b214031bd10d11e48c7d83
extra-deps:
  - mqtt-0.2.0.0
  - socket-0.8.0.1
  - socket-unix-0.2.0.0
  - aeson-1.1.0.0
  - websockets-0.10.0.0
  - tls-1.3.10
flags: {}
extra-package-dbs: []
