resolver: lts-7.19
packages:
  - '.'
#  - '../haskell-mqtt'
  - location:
      git: https://github.com/lpeterse/haskell-mqtt.git
      commit: bbd61a3fd1051897eeb3fd6d439a94a7fdd247d4
extra-deps:
  - mqtt-0.1.1.0
  - socket-0.8.0.1
  - socket-unix-0.2.0.0
  - aeson-1.1.0.0
  - websockets-0.10.0.0
flags: {}
extra-package-dbs: []
